# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Pod-PseudoPod
version:      0.08
version_from: lib/Pod/PseudoPod.pm
installdirs:  site
requires:
    Pod::Simple:                   2.05
    Text::Wrap:                    98.112902

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
